### ISSUE TITLE
It does'nt work with a known password

### ISSUE THREAD

**Issue by mkx32083** [samueltardieu/findkeepassword#6]
Hello,

first many thanks for sharing your work.
I tried it with a known password in the list and got "No working password found".
Ubuntu 20.04 5.4.0-65-generic
KeePass 2.44
Package: rustc Version: 1.47.0+dfsg1+llvm-1ubuntu1~20.04.1
findkeepassword 1.0.0

Thank you

**Comment by mkx32083** [comment]
Keepass password database 2.x KDBX

**Comment by Dafium** [comment]
Same here, i tried it and it doesn't works :(

**Comment by samueltardieu** [comment]
If your database is not in the kdbx4 format, it will not work. Are you sure your password file is using the kdbx4 format?

**Comment by Dafium** [comment]
Actually, my database was in kdbx4 format, I guess I did something else wrong.

When I executed the code, it tried every possibility at lightning speed (while my database had 5s iteration). Maybe i've just done something wrong on my side but I guess i'm not the first and wouldn't be the last.

Maybe a kind of error handling would be a great improvement to this tool ?

**Comment by samueltardieu** [comment]
@Dafium Could you try again with the current sources? I have switched kdbx libraries, and added Argon2id support to kdbx-rs.

**Comment by Dafium** [comment]
I did try again and unfortunately it directly crashed for some reasons
![image](https://user-images.githubusercontent.com/75167369/214372127-eaca1e9c-8f03-4df2-92bd-df21f17b1ee8.png)
